@HostAddress = http://localhost:5015/api/mevora

### 1. Test Ping Request (Should succeed and return Pong response)
POST {{HostAddress}}/ping
Content-Type: application/json

{
  "message": "Hello Mevora"
}

### 2. Test Ping Request Validation (Should fail validation because length < 3)
POST {{HostAddress}}/ping
Content-Type: application/json

{
  "message": "Hi"
}

### 3. Test PrintLog Command (No response, fire and forget style)
POST {{HostAddress}}/log
Content-Type: application/json

{
  "logText": "This is a test log coming from UI"
}

### 4. Test UserRegistered Event (Should trigger two multiple message processors)
POST {{HostAddress}}/register
Content-Type: application/json

{
  "username": "coder_arda",
  "registeredAt": "2026-04-13T10:00:00Z"
}
